classdef constant_activity
    properties ( Constant = true )
       SESSION_ADD_ACTIVITY = 'SESSION_ADD';
       EEG_ACTIVITY_ADD_ACTIVITY = 'EEG_ACTIVITY_ADD';
       STIMULATION_ADD_ACTIVITY = 'STIMULATION_ADD';
       EEG_ACTIVITY_AND_STIMULATION_GET_ACTIVITY = 'EEG_ACTIVITY_AND_STIMULATION_GET';
       REGRESSION_MODEL_UPDATE_ACTIVITY = 'REGRESSION_MODEL_UPDATE';
       REGRESSION_MODEL_GET_ACTIVITY = 'REGRESSION_MODEL_GET';
       REGRESSION_MODEL_ADD_ACTIVITY = 'REGRESSION_MODEL_ADD';
    end    
end

