classdef constant_activity
    properties ( Constant = true )
       SESSION_ADD_ACTIVITY = 'SESSION_ADD';
       EEG_ACTIVITY_ADD_ACTIVITY = 'EEG_ACTIVITY_ADD';
       STIMULATION_ADD_ACTIVITY = 'STIMULATION_ADD';
       EEG_ACTIVITY_AND_STIMULATION_GET_ACTIVITY = 'EEG_ACTIVITY_AND_STIMULATION_GET';
    end    
end

